### ISSUE TITLE
Session information fields can differ if not charging at home.

### ISSUE THREAD

**Issue by crkochan** [mbillow/python-chargepoint#2]
The `client.get_charging_session(charging.session_id)` call can fail with a KeyError if a user is not currently charging at home.

In this case, I am charging at a company provided station, and the debug log of the session JSON payload is missing three fields that seem to be present when at a home station.

- pricing_spec_id
- has_utility_info
- is_home_charger

A switch to [using dict.get()](https://docs.python.org/3/library/stdtypes.html#dict.get) in session.py should be sufficient to fix the immediate problem, although I haven't checked to see if this introduces any regressions elsewhere in the module.

**Comment by crkochan** [comment]
For reference, here is the session payload I got from debug output that is missing fields.

```
{
	'charging_status': {
		'country': 'United States',
		'miles_added_per_hour': 19.4555844,
		'city': 'Cupertino',
		'purpose': 'PERSONAL',
		'power_kw_display': '6.17',
		'is_purpose_finalized': True,
		'update_period': 300000,
		'lon': -122.0523452758789,
		'power_kw': 6.176376,
		'session_time': 5744000,
		'has_charging_receipt': False,
		'payment_completed': True,
		'energy_kwh': 9.744398,
		'device_name': 'APPLE / RW06 6',
		'api_flag': False,
		'outlet_number': 2,
		'state_name': 'California',
		'organization_currency': 'USD',
		'currency_iso_code': 'USD',
		'current_charging': 'in_use',
		'lat': 37.31736373901367,
		'vehicle_info': {
			'year': 2017,
			'ev_range': 315,
			'is_primary_vehicle': True,
			'model': 'Model S',
			'battery_capacity': 100.0,
			'vehicle_id': 1136411,
			'make': 'Tesla'
		},
		'port_level': 2,
		'charging_time': 5688000,
		'device_id': 91009,
		'company_id': 130,
		'address1': '6 Results Way',
		'energy_kwh_display': '9.74',
		'session_id': 1560847971,
		'update_data': [{
			'energy_kwh': 0.0,
			'power_kw': 0.0,
			'timestamp': 1667230220000
		}, {
			'energy_kwh': 0.015767,
			'power_kw': 6.15869,
			'timestamp': 1667230245000
		}, {
			'energy_kwh': 0.050012,
			'power_kw': 6.166458,
			'timestamp': 1667230269000
		}, {
			'energy_kwh': 0.135753,
			'power_kw': 6.176763,
			'timestamp': 1667230317000
		}, {
			'energy_kwh': 0.487729,
			'power_kw': 6.177428,
			'timestamp': 1667230524000
		}, {
			'energy_kwh': 1.00441,
			'power_kw': 6.212339,
			'timestamp': 1667230824000
		}, {
			'energy_kwh': 1.522412,
			'power_kw': 6.220064,
			'timestamp': 1667231124000
		}, {
			'energy_kwh': 2.04226,
			'power_kw': 6.234741,
			'timestamp': 1667231424000
		}, {
			'energy_kwh': 2.557656,
			'power_kw': 6.166248,
			'timestamp': 1667231724000
		}, {
			'energy_kwh': 3.079451,
			'power_kw': 6.15346,
			'timestamp': 1667232024000
		}, {
			'energy_kwh': 3.584599,
			'power_kw': 6.166291,
			'timestamp': 1667232324000
		}, {
			'energy_kwh': 4.098831,
			'power_kw': 6.174231,
			'timestamp': 1667232624000
		}, {
			'energy_kwh': 4.614923,
			'power_kw': 6.166935,
			'timestamp': 1667232924000
		}, {
			'energy_kwh': 5.127269,
			'power_kw': 6.141758,
			'timestamp': 1667233224000
		}, {
			'energy_kwh': 5.638959,
			'power_kw': 6.141186,
			'timestamp': 1667233524000
		}, {
			'energy_kwh': 6.14965,
			'power_kw': 6.148481,
			'timestamp': 1667233824000
		}, {
			'energy_kwh': 6.66219,
			'power_kw': 6.148911,
			'timestamp': 1667234124000
		}, {
			'energy_kwh': 7.174942,
			'power_kw': 6.155348,
			'timestamp': 1667234424000
		}, {
			'energy_kwh': 7.689803,
			'power_kw': 6.15921,
			'timestamp': 1667234724000
		}, {
			'energy_kwh': 8.203352,
			'power_kw': 6.164932,
			'timestamp': 1667235024000
		}, {
			'energy_kwh': 8.717238,
			'power_kw': 6.171227,
			'timestamp': 1667235324000
		}, {
			'energy_kwh': 9.22977,
			'power_kw': 6.172085,
			'timestamp': 1667235624000
		}, {
			'energy_kwh': 9.744398,
			'power_kw': 6.176376,
			'timestamp': 1667235924000
		}],
		'zipcode': '95014',
		'last_update_data_timestamp': 1667235924000,
		'start_time': 1667230180000,
		'payment_type': 'free',
		'total_amount': 0.0,
		'company_name': 'APPLE',
		'enable_stop_charging': True,
		'start_offset': -25200,
		'miles_added': 30.6948537,
		'stop_charge_supported': True
	}
}
```

**Comment by crkochan** [comment]
This is the traceback I'm seeing in the Home Assistant CP component.

```
2022-10-31 09:05:12.170 ERROR (MainThread) [custom_components.chargepoint] Unexpected error fetching chargepoint data: 'pricing_spec_id'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/chargepoint/__init__.py", line 140, in async_update_data
    crg_session: ChargingSession = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/python_chargepoint/client.py", line 42, in check_login
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/python_chargepoint/client.py", line 362, in get_charging_session
    return ChargingSession(session_id=session_id, client=self)
  File "/usr/local/lib/python3.10/site-packages/python_chargepoint/session.py", line 152, in __init__
    self._get()
  File "/usr/local/lib/python3.10/site-packages/python_chargepoint/session.py", line 223, in _get
    self.pricing_spec_id = status["pricing_spec_id"]
KeyError: 'pricing_spec_id'
```

**Comment by ryansun96** [comment]
@mbillow Can you release a new version with this fix and update the HA integration too? Thanks!
